package graphic;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;

public interface ArenaConfiguration {
	static final int WIDTH = 1280;
	static final int HEIGHT = 400;
	static final Dimension SIZE_ARENA = new Dimension(WIDTH, HEIGHT);
	static final Color BACKGROUND_COLOR = Color.white;	
	static final String TITLE = "Super Awesome Fighters Battle";
	static final int NEAR = 30;
	static final int FAR = 31;
	static final String PATH_IMAGES = "D:/Dropbox/Dropbox/Software Construction/workspace/SC12/images/";
	static final String BLOCK_HIGH_L = "block_high_l.jpg";
	static final String BLOCK_LOW_L = "block_low_l.jpg";
	static final String KICK_HIGH_L = "kick_high_l.jpg";
	static final String KICK_LOW_L = "kick_low_l.jpg";
	static final String PUNCH_HIGH_L = "punch_high_l.jpg";
	static final String PUNCH_LOW_L = "punch_low_l.jpg";
	static final String RELAXED_L = "relaxed_l.jpg";
	static final String JUMP_L = "jump_l.jpg";
	static final String CROUCH_L = "crouch_l.jpg";
	static final String DEAD_L = "dead_l.jpg";
	static final String WINNER_L = "winner_l.jpg";
	static final String BLOCK_HIGH_R = "block_high_r.jpg";
	static final String BLOCK_LOW_R = "block_low_r.jpg";
	static final String KICK_HIGH_R = "kick_high_r.jpg";
	static final String KICK_LOW_R = "kick_low_r.jpg";
	static final String PUNCH_HIGH_R = "punch_high_r.jpg";
	static final String PUNCH_LOW_R = "punch_low_r.jpg";
	static final String RELAXED_R = "relaxed_r.jpg";
	static final String CROUCH_R = "crouch_r.jpg";
	static final String JUMP_R = "jump_r.jpg";
	static final String DEAD_R = "dead_r.jpg";
	static final String WINNER_R = "winner_r.jpg";
	static final File blockHighL = new File (PATH_IMAGES + BLOCK_HIGH_L);
	static final File blockLowL = new File (PATH_IMAGES + BLOCK_LOW_L);
	static final File kickHighL = new File (PATH_IMAGES + KICK_HIGH_L);
	static final File kickLowL = new File (PATH_IMAGES + KICK_LOW_L);
	static final File punchkHighL = new File (PATH_IMAGES + PUNCH_HIGH_L);
	static final File punchLowL = new File (PATH_IMAGES + PUNCH_LOW_L);
	static final File deadL = new File (PATH_IMAGES + DEAD_L);
	static final File winnerL = new File (PATH_IMAGES + WINNER_L);
	static final File jumpL = new File (PATH_IMAGES + JUMP_L);
	static final File crouchL = new File (PATH_IMAGES + CROUCH_L);
	static final File blockHighR = new File (PATH_IMAGES + BLOCK_HIGH_R);
	static final File blockLowR = new File (PATH_IMAGES + BLOCK_LOW_R);
	static final File kickHighR = new File (PATH_IMAGES + KICK_HIGH_R);
	static final File kickLowR = new File (PATH_IMAGES + KICK_LOW_R);
	static final File punchkHighR = new File (PATH_IMAGES + PUNCH_HIGH_R);
	static final File punchLowR = new File (PATH_IMAGES + PUNCH_LOW_R);
	static final File deadR = new File (PATH_IMAGES + DEAD_R);
	static final File winnerR = new File (PATH_IMAGES + WINNER_R);
	static final File jumpR = new File (PATH_IMAGES + JUMP_R);
	static final File crouchR = new File (PATH_IMAGES + CROUCH_R);
	static final File relaxedL = new File (PATH_IMAGES + RELAXED_L);
	static final File relaxedR = new File (PATH_IMAGES + RELAXED_R);
}
