/* Generated By:JJTree: Do not edit this line. ASTFighterNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFighterNode extends SimpleNode {
  public ASTFighterNode(int id) {
    super(id);
  }

  public ASTFighterNode(FighterGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FighterGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d5a1cb14fbba7f13819f2228f2ed5be7 (do not edit this line) */
