/* Generated By:JJTree&JavaCC: Do not edit this line. FighterGrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FighterGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGNMENT = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int CHOOSE = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int STARTBRACE = 11;
  /** RegularExpression Id. */
  int ENDBRACE = 12;
  /** RegularExpression Id. */
  int LIST_OPEN = 13;
  /** RegularExpression Id. */
  int LIST_CLOSE = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int CHARACTER = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "<NUMBER>",
    "\"choose\"",
    "\"or\"",
    "\"and\"",
    "<IDENTIFIER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<DIGIT>",
    "<CHARACTER>",
    "\"(\"",
    "\")\"",
  };

}
