/* Generated By:JavaCC: Do not edit this line. safTreeConstants.java Version 5.0 */
package safparser;

public interface safTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFIGHTEREXPRESSION = 1;
  public int JJTMOVEEXPRESSION = 2;
  public int JJTATTACKEXPRESSION = 3;
  public int JJTCHARACTERISTICEXPRESSION = 4;
  public int JJTACTIONEXPRESSION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTINTEGER = 7;


  public String[] jjtNodeName = {
    "Start",
    "FighterExpression",
    "MoveExpression",
    "AttackExpression",
    "CharacteristicExpression",
    "ActionExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=d2e54393f87dd7d77709c5b62677dcd0 (do not edit this line) */
