/* Generated By:JavaCC: Do not edit this line. safTreeConstants.java Version 5.0 */
package safparser;

public interface safTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFIGHTEREXPRESSION = 1;
  public int JJTCHARACTERISTICEXPRESSIONS = 2;
  public int JJTACTIONEXPRESSIONS = 3;
  public int JJTMOVEEXPRESSION = 4;
  public int JJTATTACKEXPRESSION = 5;
  public int JJTATTACK = 6;
  public int JJTCHARACTERISTICEXPRESSION = 7;
  public int JJTACTIONEXPRESSION = 8;
  public int JJTCONDITIONEXPRESSION = 9;
  public int JJTCONNECTIVE = 10;
  public int JJTCONDITION = 11;
  public int JJTSTRENGTH = 12;
  public int JJTMOVE = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTINTEGER = 15;


  public String[] jjtNodeName = {
    "Start",
    "FighterExpression",
    "CharacteristicExpressions",
    "ActionExpressions",
    "MoveExpression",
    "AttackExpression",
    "Attack",
    "CharacteristicExpression",
    "ActionExpression",
    "ConditionExpression",
    "Connective",
    "Condition",
    "Strength",
    "Move",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=21f596281578e4a44d0b457f152ceaab (do not edit this line) */
