/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class APunchLowFightActionType extends PFightActionType
{
    private TPunchLow _punchLow_;

    public APunchLowFightActionType()
    {
        // Constructor
    }

    public APunchLowFightActionType(
        @SuppressWarnings("hiding") TPunchLow _punchLow_)
    {
        // Constructor
        setPunchLow(_punchLow_);

    }

    @Override
    public Object clone()
    {
        return new APunchLowFightActionType(
            cloneNode(this._punchLow_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPunchLowFightActionType(this);
    }

    public TPunchLow getPunchLow()
    {
        return this._punchLow_;
    }

    public void setPunchLow(TPunchLow node)
    {
        if(this._punchLow_ != null)
        {
            this._punchLow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._punchLow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._punchLow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._punchLow_ == child)
        {
            this._punchLow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._punchLow_ == oldChild)
        {
            setPunchLow((TPunchLow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
