/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TPunchLow extends Token
{
    public TPunchLow()
    {
        super.setText("punch_low");
    }

    public TPunchLow(int line, int pos)
    {
        super.setText("punch_low");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPunchLow(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPunchLow(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPunchLow text.");
    }
}
