/* Generated By:JavaCC: Do not edit this line. SafTreeConstants.java Version 5.0 */
package saf;

public interface SafTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTRENGTH = 1;
  public int JJTCONDITION = 2;


  public String[] jjtNodeName = {
    "Parse",
    "Strength",
    "Condition",
  };
}
/* JavaCC - OriginalChecksum=71ce2434670be2e8d62e9d5f402578fb (do not edit this line) */
