/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class AKickLowFightActionType extends PFightActionType
{
    private TKickLow _kickLow_;

    public AKickLowFightActionType()
    {
        // Constructor
    }

    public AKickLowFightActionType(
        @SuppressWarnings("hiding") TKickLow _kickLow_)
    {
        // Constructor
        setKickLow(_kickLow_);

    }

    @Override
    public Object clone()
    {
        return new AKickLowFightActionType(
            cloneNode(this._kickLow_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKickLowFightActionType(this);
    }

    public TKickLow getKickLow()
    {
        return this._kickLow_;
    }

    public void setKickLow(TKickLow node)
    {
        if(this._kickLow_ != null)
        {
            this._kickLow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kickLow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kickLow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kickLow_ == child)
        {
            this._kickLow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kickLow_ == oldChild)
        {
            setKickLow((TKickLow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
