/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TJump extends Token
{
    public TJump()
    {
        super.setText("jump");
    }

    public TJump(int line, int pos)
    {
        super.setText("jump");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TJump(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJump(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TJump text.");
    }
}
