/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class AWalkTowardsMoveActionType extends PMoveActionType
{
    private TWalkTowards _walkTowards_;

    public AWalkTowardsMoveActionType()
    {
        // Constructor
    }

    public AWalkTowardsMoveActionType(
        @SuppressWarnings("hiding") TWalkTowards _walkTowards_)
    {
        // Constructor
        setWalkTowards(_walkTowards_);

    }

    @Override
    public Object clone()
    {
        return new AWalkTowardsMoveActionType(
            cloneNode(this._walkTowards_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWalkTowardsMoveActionType(this);
    }

    public TWalkTowards getWalkTowards()
    {
        return this._walkTowards_;
    }

    public void setWalkTowards(TWalkTowards node)
    {
        if(this._walkTowards_ != null)
        {
            this._walkTowards_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._walkTowards_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._walkTowards_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._walkTowards_ == child)
        {
            this._walkTowards_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._walkTowards_ == oldChild)
        {
            setWalkTowards((TWalkTowards) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
