/* Generated By:JJTree: Do not edit this line. ASTFighter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFighter extends SimpleNode {
  public ASTFighter(int id) {
    super(id);
  }

  public ASTFighter(FighterGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FighterGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db9a6f3cd4b36b8f592e505f7348c3bf (do not edit this line) */
