/* Generated By:JavaCC: Do not edit this line. FighterGrammarTreeConstants.java Version 5.0 */
public interface FighterGrammarTreeConstants
{
  public int JJTFIGHTERNODE = 0;
  public int JJTFIGHTER = 1;
  public int JJTVOID = 2;
  public int JJTFIGHTERPERSONALITY = 3;
  public int JJTFIGHTERCHARACTERISTICSRULE = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTCHARACTERISTICVALUE = 7;


  public String[] jjtNodeName = {
    "FighterNode",
    "Fighter",
    "void",
    "FighterPersonality",
    "fighterCharacteristicsRule",
    "Identifier",
    "Assignment",
    "CharacteristicValue",
  };
}
/* JavaCC - OriginalChecksum=86d2f17caf0b55af3d2232a595993753 (do not edit this line) */
