/* Generated By:JavaCC: Do not edit this line. FighterGrammarVisitor.java Version 5.0 */
public interface FighterGrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTFighterNode node, Object data);
  public Object visit(ASTFighter node, Object data);
  public Object visit(ASTFighterPersonality node, Object data);
  public Object visit(ASTfighterCharacteristicsRule node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTCharacteristicValue node, Object data);
}
/* JavaCC - OriginalChecksum=5978801266b43f9a17d6dff541beac56 (do not edit this line) */
