/* Generated By:JavaCC: Do not edit this line. FighterGrammarTreeConstants.java Version 5.0 */
public interface FighterGrammarTreeConstants
{
  public int JJTFIGHTERNODE = 0;
  public int JJTFIGHTER = 1;
  public int JJTVOID = 2;
  public int JJTFIGHTERPERSONALITY = 3;
  public int JJTFIGHTERCHARACTARISTIC = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTNUMBER = 7;


  public String[] jjtNodeName = {
    "FighterNode",
    "Fighter",
    "void",
    "FighterPersonality",
    "FighterCharactaristic",
    "Identifier",
    "Assignment",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=7de2dbeff4dcc16a357d0e01f72a9948 (do not edit this line) */
