/* Generated By:JJTree&JavaCC: Do not edit this line. FighterGrammarConstants.java */
package foo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FighterGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRENGTH_VALUE = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int CHOOSE = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int LSQBRACKET = 12;
  /** RegularExpression Id. */
  int RSQBRACKET = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int LBRACKET = 16;
  /** RegularExpression Id. */
  int RBRACKET = 17;
  /** RegularExpression Id. */
  int MOVE = 18;
  /** RegularExpression Id. */
  int STRENGTH = 19;
  /** RegularExpression Id. */
  int ATTACK = 20;
  /** RegularExpression Id. */
  int CONDITION = 21;
  /** RegularExpression Id. */
  int NAME = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<STRENGTH_VALUE>",
    "<AND>",
    "<OR>",
    "\"choose\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<MOVE>",
    "<STRENGTH>",
    "<ATTACK>",
    "<CONDITION>",
    "<NAME>",
  };

}
