/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ARunAwayMoveActionType extends PMoveActionType
{
    private TRunAway _runAway_;

    public ARunAwayMoveActionType()
    {
        // Constructor
    }

    public ARunAwayMoveActionType(
        @SuppressWarnings("hiding") TRunAway _runAway_)
    {
        // Constructor
        setRunAway(_runAway_);

    }

    @Override
    public Object clone()
    {
        return new ARunAwayMoveActionType(
            cloneNode(this._runAway_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARunAwayMoveActionType(this);
    }

    public TRunAway getRunAway()
    {
        return this._runAway_;
    }

    public void setRunAway(TRunAway node)
    {
        if(this._runAway_ != null)
        {
            this._runAway_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._runAway_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._runAway_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._runAway_ == child)
        {
            this._runAway_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._runAway_ == oldChild)
        {
            setRunAway((TRunAway) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
