/* Generated By:JavaCC: Do not edit this line. SafConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SafConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGNMENT = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int CHOOSE = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int NUM = 11;
  /** RegularExpression Id. */
  int LEFTPARENTHESIS = 12;
  /** RegularExpression Id. */
  int RIGHTPARENTHESIS = 13;
  /** RegularExpression Id. */
  int LEFTCURLYBRACKET = 14;
  /** RegularExpression Id. */
  int RIGHTCURLYBRACKET = 15;
  /** RegularExpression Id. */
  int LEFTSQAREBRACKET = 16;
  /** RegularExpression Id. */
  int RIGHTSQAREBRACKET = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"=\"",
    "\"and\"",
    "\"or\"",
    "\"choose\"",
    "<IDENTIFIER>",
    "<NUM>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
