/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TPunchHigh extends Token
{
    public TPunchHigh()
    {
        super.setText("punch_high");
    }

    public TPunchHigh(int line, int pos)
    {
        super.setText("punch_high");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPunchHigh(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPunchHigh(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPunchHigh text.");
    }
}
