/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ACrouchMoveActionType extends PMoveActionType
{
    private TCrouch _crouch_;

    public ACrouchMoveActionType()
    {
        // Constructor
    }

    public ACrouchMoveActionType(
        @SuppressWarnings("hiding") TCrouch _crouch_)
    {
        // Constructor
        setCrouch(_crouch_);

    }

    @Override
    public Object clone()
    {
        return new ACrouchMoveActionType(
            cloneNode(this._crouch_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACrouchMoveActionType(this);
    }

    public TCrouch getCrouch()
    {
        return this._crouch_;
    }

    public void setCrouch(TCrouch node)
    {
        if(this._crouch_ != null)
        {
            this._crouch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crouch_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._crouch_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._crouch_ == child)
        {
            this._crouch_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._crouch_ == oldChild)
        {
            setCrouch((TCrouch) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
