/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TKickPower extends Token
{
    public TKickPower()
    {
        super.setText("kickPower");
    }

    public TKickPower(int line, int pos)
    {
        super.setText("kickPower");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKickPower(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKickPower(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKickPower text.");
    }
}
