/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class AKickReachProgramCharacteristic extends PProgramCharacteristic
{
    private PProgramKickReach _programKickReach_;

    public AKickReachProgramCharacteristic()
    {
        // Constructor
    }

    public AKickReachProgramCharacteristic(
        @SuppressWarnings("hiding") PProgramKickReach _programKickReach_)
    {
        // Constructor
        setProgramKickReach(_programKickReach_);

    }

    @Override
    public Object clone()
    {
        return new AKickReachProgramCharacteristic(
            cloneNode(this._programKickReach_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAKickReachProgramCharacteristic(this);
    }

    public PProgramKickReach getProgramKickReach()
    {
        return this._programKickReach_;
    }

    public void setProgramKickReach(PProgramKickReach node)
    {
        if(this._programKickReach_ != null)
        {
            this._programKickReach_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programKickReach_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programKickReach_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programKickReach_ == child)
        {
            this._programKickReach_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programKickReach_ == oldChild)
        {
            setProgramKickReach((PProgramKickReach) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
