/* Generated By:JavaCC: Do not edit this line. FighterGrammarTreeConstants.java Version 5.0 */
package foo;

public interface FighterGrammarTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTGETBOT = 1;
  public int JJTSTRENGTH = 2;
  public int JJTBEHAVIOURITEM = 3;


  public String[] jjtNodeName = {
    "Parse",
    "getBot",
    "Strength",
    "BehaviourItem",
  };
}
/* JavaCC - OriginalChecksum=45b174ed5e6bcf6b5c4fb33a34d36e8e (do not edit this line) */
