/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ARunTowardsMoveActionType extends PMoveActionType
{
    private TRunTowards _runTowards_;

    public ARunTowardsMoveActionType()
    {
        // Constructor
    }

    public ARunTowardsMoveActionType(
        @SuppressWarnings("hiding") TRunTowards _runTowards_)
    {
        // Constructor
        setRunTowards(_runTowards_);

    }

    @Override
    public Object clone()
    {
        return new ARunTowardsMoveActionType(
            cloneNode(this._runTowards_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARunTowardsMoveActionType(this);
    }

    public TRunTowards getRunTowards()
    {
        return this._runTowards_;
    }

    public void setRunTowards(TRunTowards node)
    {
        if(this._runTowards_ != null)
        {
            this._runTowards_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._runTowards_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._runTowards_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._runTowards_ == child)
        {
            this._runTowards_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._runTowards_ == oldChild)
        {
            setRunTowards((TRunTowards) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
