/* Generated By:JJTree&JavaCC: Do not edit this line. safConstants.java */
package safparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface safConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHOOSE = 7;
  /** RegularExpression Id. */
  int CONDITION = 8;
  /** RegularExpression Id. */
  int MOVE = 9;
  /** RegularExpression Id. */
  int STRENGTH = 10;
  /** RegularExpression Id. */
  int ATTACK = 11;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"choose\"",
    "<CONDITION>",
    "<MOVE>",
    "<STRENGTH>",
    "<ATTACK>",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
  };

}
