/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ABlockHighFightActionType extends PFightActionType
{
    private TBlockHigh _blockHigh_;

    public ABlockHighFightActionType()
    {
        // Constructor
    }

    public ABlockHighFightActionType(
        @SuppressWarnings("hiding") TBlockHigh _blockHigh_)
    {
        // Constructor
        setBlockHigh(_blockHigh_);

    }

    @Override
    public Object clone()
    {
        return new ABlockHighFightActionType(
            cloneNode(this._blockHigh_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockHighFightActionType(this);
    }

    public TBlockHigh getBlockHigh()
    {
        return this._blockHigh_;
    }

    public void setBlockHigh(TBlockHigh node)
    {
        if(this._blockHigh_ != null)
        {
            this._blockHigh_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockHigh_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockHigh_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockHigh_ == child)
        {
            this._blockHigh_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockHigh_ == oldChild)
        {
            setBlockHigh((TBlockHigh) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
