/* Generated By:JJTree&JavaCC: Do not edit this line. eg2Constants.java */
package SAFchecker;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface eg2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE_ACTION = 7;
  /** RegularExpression Id. */
  int MOVE_ACTION_TYPE = 8;
  /** RegularExpression Id. */
  int WALK_TO = 9;
  /** RegularExpression Id. */
  int WALK_AW = 10;
  /** RegularExpression Id. */
  int RUN_TO = 11;
  /** RegularExpression Id. */
  int RUN_AW = 12;
  /** RegularExpression Id. */
  int JUMP = 13;
  /** RegularExpression Id. */
  int CROUCH = 14;
  /** RegularExpression Id. */
  int STAND = 15;
  /** RegularExpression Id. */
  int FIGHT_ACTION = 16;
  /** RegularExpression Id. */
  int FIGHT_ACTION_TYPE = 17;
  /** RegularExpression Id. */
  int BLOCK_LOW = 18;
  /** RegularExpression Id. */
  int BLOCK_HIGH = 19;
  /** RegularExpression Id. */
  int PUNCH_LOW = 20;
  /** RegularExpression Id. */
  int PUNCH_HIGH = 21;
  /** RegularExpression Id. */
  int KICK_LOW = 22;
  /** RegularExpression Id. */
  int KICK_HIGH = 23;
  /** RegularExpression Id. */
  int CONDITIONS = 24;
  /** RegularExpression Id. */
  int CONDITION_TYPE = 25;
  /** RegularExpression Id. */
  int ALWAYS = 26;
  /** RegularExpression Id. */
  int NEAR = 27;
  /** RegularExpression Id. */
  int FAR = 28;
  /** RegularExpression Id. */
  int MUCH_STR = 29;
  /** RegularExpression Id. */
  int STRONGER = 30;
  /** RegularExpression Id. */
  int EVEN = 31;
  /** RegularExpression Id. */
  int WEAKER = 32;
  /** RegularExpression Id. */
  int MUCH_WEA = 33;
  /** RegularExpression Id. */
  int NUMBER = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int CHARACTERISTICS = 36;
  /** RegularExpression Id. */
  int PUNCH_REACH = 37;
  /** RegularExpression Id. */
  int PUNCH_POWER = 38;
  /** RegularExpression Id. */
  int KICK_REACH = 39;
  /** RegularExpression Id. */
  int KICK_POWER = 40;
  /** RegularExpression Id. */
  int CHOOSE = 41;
  /** RegularExpression Id. */
  int CH_WRD = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int AND_WRD = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int OR_WRD = 46;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 47;
  /** RegularExpression Id. */
  int LEFT_PAR = 48;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 49;
  /** RegularExpression Id. */
  int RIGHT_PAR = 50;
  /** RegularExpression Id. */
  int LEFT_SQBRACKET = 51;
  /** RegularExpression Id. */
  int LEFT_SQBR = 52;
  /** RegularExpression Id. */
  int RIGHT_SQBRACKET = 53;
  /** RegularExpression Id. */
  int RIGHT_SQBR = 54;
  /** RegularExpression Id. */
  int LEFT_CURLBRACKET = 55;
  /** RegularExpression Id. */
  int LEFT_CURLBR = 56;
  /** RegularExpression Id. */
  int RIGHT_CURLBRACKET = 57;
  /** RegularExpression Id. */
  int RIGHT_CURLBR = 58;
  /** RegularExpression Id. */
  int IDENTIFIER = 59;
  /** RegularExpression Id. */
  int LETTER = 60;
  /** RegularExpression Id. */
  int DIGIT = 61;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<MOVE_ACTION>",
    "<MOVE_ACTION_TYPE>",
    "\"walk_towards\"",
    "\"walk_away\"",
    "\"run_towards\"",
    "\"run_away\"",
    "\"jump\"",
    "\"crouch\"",
    "\"stand\"",
    "<FIGHT_ACTION>",
    "<FIGHT_ACTION_TYPE>",
    "\"block_low\"",
    "\"block_high\"",
    "\"punch_low\"",
    "\"punch_high\"",
    "\"kick_low\"",
    "\"kick_high\"",
    "<CONDITIONS>",
    "<CONDITION_TYPE>",
    "\"always\"",
    "\"near\"",
    "\"far\"",
    "\"much_stronger\"",
    "\"stronger\"",
    "\"even\"",
    "\"weaker\"",
    "\"much_weaker\"",
    "<NUMBER>",
    "<NUM>",
    "<CHARACTERISTICS>",
    "\"punchReach\"",
    "\"punchPower\"",
    "\"kickReach\"",
    "\"kickPower\"",
    "<CHOOSE>",
    "\"choose\"",
    "<AND>",
    "\"and\"",
    "<OR>",
    "\"or\"",
    "<LEFT_PARENTHESIS>",
    "<LEFT_PAR>",
    "<RIGHT_PARENTHESIS>",
    "<RIGHT_PAR>",
    "<LEFT_SQBRACKET>",
    "<LEFT_SQBR>",
    "<RIGHT_SQBRACKET>",
    "<RIGHT_SQBR>",
    "<LEFT_CURLBRACKET>",
    "<LEFT_CURLBR>",
    "<RIGHT_CURLBRACKET>",
    "<RIGHT_CURLBR>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
  };

}
