/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
package SAFparser;

public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTBEHAVIOUR = 2;
  public int JJTPERSONALITY = 3;
  public int JJTCHOOSEMOVEACTION = 4;
  public int JJTCHOOSEFIGHTACTION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTMOVEACTION = 7;
  public int JJTFIGHTACTION = 8;
  public int JJTCHOOSE = 9;
  public int JJTCONDITIONS = 10;
  public int JJTNUMBER0_9 = 11;
  public int JJTLEFTPARENTHESIS = 12;
  public int JJTRIGHTPARENTHESIS = 13;
  public int JJTLEFTSQBR = 14;
  public int JJTRIGHTSQBR = 15;
  public int JJTLEFTCURLBR = 16;
  public int JJTRIGHTCURLBR = 17;
  public int JJTCHARACTERISTICS = 18;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Behaviour",
    "Personality",
    "ChooseMoveAction",
    "ChooseFightAction",
    "Identifier",
    "MoveAction",
    "FightAction",
    "Choose",
    "Conditions",
    "Number0_9",
    "LeftParenthesis",
    "RightParenthesis",
    "LeftSQBR",
    "RightSQBR",
    "LeftCURLBR",
    "RightCURLBR",
    "Characteristics",
  };
}
/* JavaCC - OriginalChecksum=946511994b6b27e66f250d04e473f80e (do not edit this line) */
