/* Generated By:JavaCC: Do not edit this line. FighterGrammarTreeConstants.java Version 5.0 */
package grammar;

public interface FighterGrammarTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTGETBOT = 1;
  public int JJTSTRENGTH = 2;
  public int JJTBEHAVIOURITEM = 3;
  public int JJTCONDITION = 4;
  public int JJTACTION = 5;


  public String[] jjtNodeName = {
    "Parse",
    "getBot",
    "Strength",
    "BehaviourItem",
    "Condition",
    "Action",
  };
}
/* JavaCC - OriginalChecksum=bf03044da741e1f4582132cd7c098896 (do not edit this line) */
