/* Generated By:JavaCC: Do not edit this line. eg2TreeConstants.java Version 5.0 */
package SAFchecker;

public interface eg2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTBEHAVIOUR = 2;
  public int JJTPERSONALITY = 3;
  public int JJTCHOOSEMOVEACTION = 4;
  public int JJTCHOOSEFIGHTACTION = 5;
  public int JJTIDENTIFIER = 6;
  public int JJTMOVEACTION = 7;
  public int JJTFIGHTACTION = 8;
  public int JJTCHOOSE = 9;
  public int JJTAND = 10;
  public int JJTOR = 11;
  public int JJTCONDITIONS = 12;
  public int JJTCONDITIONDANDOR = 13;
  public int JJTCONDITIONSWITHANDOR = 14;
  public int JJTNUMBER0_9 = 15;
  public int JJTLEFTPARENTHESIS = 16;
  public int JJTRIGHTPARENTHESIS = 17;
  public int JJTLEFTSQBR = 18;
  public int JJTRIGHTSQBR = 19;
  public int JJTLEFTCURLBR = 20;
  public int JJTRIGHTCURLBR = 21;
  public int JJTCHARACTERISTICS = 22;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "Behaviour",
    "Personality",
    "ChooseMoveAction",
    "ChooseFightAction",
    "Identifier",
    "MoveAction",
    "FightAction",
    "Choose",
    "And",
    "Or",
    "Conditions",
    "conditiondAndOr",
    "conditionsWithAndOr",
    "Number0_9",
    "LeftParenthesis",
    "RightParenthesis",
    "LeftSQBR",
    "RightSQBR",
    "LeftCURLBR",
    "RightCURLBR",
    "Characteristics",
  };
}
/* JavaCC - OriginalChecksum=4e412cdcf3f683dc17385823ef075c79 (do not edit this line) */
