/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TChoose extends Token
{
    public TChoose()
    {
        super.setText("choose");
    }

    public TChoose(int line, int pos)
    {
        super.setText("choose");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TChoose(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTChoose(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TChoose text.");
    }
}
