/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TCrouch extends Token
{
    public TCrouch()
    {
        super.setText("crouch");
    }

    public TCrouch(int line, int pos)
    {
        super.setText("crouch");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCrouch(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCrouch(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCrouch text.");
    }
}
