/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TStronger extends Token
{
    public TStronger()
    {
        super.setText("stronger");
    }

    public TStronger(int line, int pos)
    {
        super.setText("stronger");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStronger(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStronger(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStronger text.");
    }
}
