/* Generated By:JJTree&JavaCC: Do not edit this line. SafConstants.java */
package saf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SafConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGNMENT = 6;
  /** RegularExpression Id. */
  int CHOOSE = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int PROPERTYVALUE = 9;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 10;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 11;
  /** RegularExpression Id. */
  int OPENCURLYBRACKET = 12;
  /** RegularExpression Id. */
  int CLOSECURLYBRACKET = 13;
  /** RegularExpression Id. */
  int OPENSQAREBRACKET = 14;
  /** RegularExpression Id. */
  int CLOSESQAREBRACKET = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"=\"",
    "\"choose\"",
    "<IDENTIFIER>",
    "<PROPERTYVALUE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
