/* Generated By:JavaCC: Do not edit this line. SafTreeConstants.java Version 5.0 */
package saf.parser;

public interface SafTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTRENGTH = 1;
  public int JJTBEHAVIORS = 2;
  public int JJTMOVES = 3;
  public int JJTATTACKS = 4;


  public String[] jjtNodeName = {
    "Parse",
    "Strength",
    "Behaviors",
    "Moves",
    "Attacks",
  };
}
/* JavaCC - OriginalChecksum=8a5554ae34601fa21f573972b341b6a0 (do not edit this line) */
