/* Generated By:JavaCC: Do not edit this line. SafTreeConstants.java Version 5.0 */
package saf.parser;

public interface SafTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTRENGTH = 1;
  public int JJTBEHAVIOR = 2;


  public String[] jjtNodeName = {
    "Parse",
    "Strength",
    "Behavior",
  };
}
/* JavaCC - OriginalChecksum=0df5ea131d73ad38850925d1baab97d0 (do not edit this line) */
