/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TBlockLow extends Token
{
    public TBlockLow()
    {
        super.setText("block_low");
    }

    public TBlockLow(int line, int pos)
    {
        super.setText("block_low");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBlockLow(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBlockLow(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBlockLow text.");
    }
}
