/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TEven extends Token
{
    public TEven()
    {
        super.setText("even");
    }

    public TEven(int line, int pos)
    {
        super.setText("even");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEven(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEven(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEven text.");
    }
}
