/*
 * Form.java
 *
 * Created on __DATE__, __TIME__
 */

package saf.game.gui;

/**
 *
 * @author  __USER__
 */
public class GameForm extends javax.swing.JFrame {

	/** Creates new form Form */
	public GameForm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelHeader = new javax.swing.JLabel();
		jPanelContent = new javax.swing.JPanel();
		jPanelBotOne1 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabelBotTwoName = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jListBotTwoChars = new javax.swing.JList();
		jScrollPane4 = new javax.swing.JScrollPane();
		jListBotTwoBehaviors = new javax.swing.JList();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButtonBotTwoLoad = new javax.swing.JButton();
		jPanelBotOne = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabelBotOneName = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListBotOneChars = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		jListBotOneBehaviors = new javax.swing.JList();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButtonBotOneLoad = new javax.swing.JButton();
		jPanelGameArea = new javax.swing.JPanel();
		jPanelGameButtons = new javax.swing.JPanel();
		jButtonStart = new javax.swing.JButton();
		jPanelArea = new saf.game.gui.component.GameArena();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(800, 500));

		jLabelHeader.setFont(new java.awt.Font("Segoe UI", 0, 36));
		jLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelHeader.setText("Welcome to the Super Awesome Fighters game!");
		jLabelHeader.setFocusable(false);
		jLabelHeader
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jPanelBotOne1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel6.setText("Fighter 2");

		jLabel7.setText("Name");

		jLabelBotTwoName.setText("Example Name");

		jListBotTwoChars
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jListBotTwoChars.setPreferredSize(new java.awt.Dimension(150, 100));
		jScrollPane3.setViewportView(jListBotTwoChars);

		jListBotTwoBehaviors
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jListBotTwoBehaviors.setPreferredSize(new java.awt.Dimension(0, 100));
		jScrollPane4.setViewportView(jListBotTwoBehaviors);

		jLabel8.setText("Characteristics");

		jLabel9.setText("Behaviors");

		jButtonBotTwoLoad.setText("Load fighter");

		javax.swing.GroupLayout jPanelBotOne1Layout = new javax.swing.GroupLayout(
				jPanelBotOne1);
		jPanelBotOne1.setLayout(jPanelBotOne1Layout);
		jPanelBotOne1Layout
				.setHorizontalGroup(jPanelBotOne1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelBotOne1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelBotOne1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelBotOne1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelBotOne1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel6)
																						.addGroup(
																								jPanelBotOne1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel7)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabelBotTwoName)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				322,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButtonBotTwoLoad))
														.addGroup(
																jPanelBotOne1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelBotOne1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel8))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelBotOne1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jScrollPane4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								283,
																								Short.MAX_VALUE))))
										.addContainerGap()));
		jPanelBotOne1Layout
				.setVerticalGroup(jPanelBotOne1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelBotOne1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelBotOne1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelBotOne1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelBotOne1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabelBotTwoName)))
														.addComponent(
																jButtonBotTwoLoad))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanelBotOne1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanelBotOne1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanelBotOne.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jLabel2.setText("Fighter 1");

		jLabel3.setText("Name");

		jLabelBotOneName.setText("Example Name");

		jListBotOneChars
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jListBotOneChars.setPreferredSize(new java.awt.Dimension(150, 100));
		jScrollPane1.setViewportView(jListBotOneChars);

		jListBotOneBehaviors
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jListBotOneBehaviors.setPreferredSize(new java.awt.Dimension(0, 100));
		jScrollPane2.setViewportView(jListBotOneBehaviors);

		jLabel4.setText("Characteristics");

		jLabel5.setText("Behaviors");

		jButtonBotOneLoad.setText("Load fighter");

		javax.swing.GroupLayout jPanelBotOneLayout = new javax.swing.GroupLayout(
				jPanelBotOne);
		jPanelBotOne.setLayout(jPanelBotOneLayout);
		jPanelBotOneLayout
				.setHorizontalGroup(jPanelBotOneLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelBotOneLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelBotOneLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelBotOneLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelBotOneLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelBotOneLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								259,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanelBotOneLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelBotOneLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addGroup(
																								jPanelBotOneLayout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel3)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabelBotOneName)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				298,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButtonBotOneLoad)))
										.addContainerGap()));
		jPanelBotOneLayout
				.setVerticalGroup(jPanelBotOneLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelBotOneLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelBotOneLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelBotOneLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanelBotOneLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabelBotOneName))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanelBotOneLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5)))
														.addComponent(
																jButtonBotOneLoad))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanelBotOneLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jPanelGameArea.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jPanelGameButtons.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(153, 153, 153)));

		jButtonStart.setText("Start duel");

		javax.swing.GroupLayout jPanelGameButtonsLayout = new javax.swing.GroupLayout(
				jPanelGameButtons);
		jPanelGameButtons.setLayout(jPanelGameButtonsLayout);
		jPanelGameButtonsLayout.setHorizontalGroup(jPanelGameButtonsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanelGameButtonsLayout.createSequentialGroup()
								.addContainerGap().addComponent(jButtonStart)
								.addContainerGap(1008, Short.MAX_VALUE)));
		jPanelGameButtonsLayout.setVerticalGroup(jPanelGameButtonsLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanelGameButtonsLayout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(jButtonStart)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanelAreaLayout = new javax.swing.GroupLayout(
				jPanelArea);
		jPanelArea.setLayout(jPanelAreaLayout);
		jPanelAreaLayout.setHorizontalGroup(jPanelAreaLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 1105, Short.MAX_VALUE));
		jPanelAreaLayout.setVerticalGroup(jPanelAreaLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 299,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanelGameAreaLayout = new javax.swing.GroupLayout(
				jPanelGameArea);
		jPanelGameArea.setLayout(jPanelGameAreaLayout);
		jPanelGameAreaLayout
				.setHorizontalGroup(jPanelGameAreaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelGameAreaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelGameAreaLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanelArea,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanelGameButtons,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanelGameAreaLayout
				.setVerticalGroup(jPanelGameAreaLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelGameAreaLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanelGameButtons,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanelArea,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(
				jPanelContent);
		jPanelContent.setLayout(jPanelContentLayout);
		jPanelContentLayout
				.setHorizontalGroup(jPanelContentLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelContentLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelContentLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanelGameArea,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanelContentLayout
																		.createSequentialGroup()
																		.addComponent(
																				jPanelBotOne,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanelBotOne1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanelContentLayout
				.setVerticalGroup(jPanelContentLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelContentLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanelContentLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jPanelBotOne1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanelBotOne,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanelGameArea,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addContainerGap()
								.addComponent(jLabelHeader)
								.addContainerGap(377, Short.MAX_VALUE))
				.addComponent(jPanelContent,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jLabelHeader)
						.addGap(18, 18, 18)
						.addComponent(jPanelContent,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GameForm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	protected javax.swing.JButton jButtonBotOneLoad;
	protected javax.swing.JButton jButtonBotTwoLoad;
	private javax.swing.JButton jButtonStart;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	protected javax.swing.JLabel jLabelBotOneName;
	protected javax.swing.JLabel jLabelBotTwoName;
	public javax.swing.JLabel jLabelHeader;
	protected javax.swing.JList jListBotOneBehaviors;
	protected javax.swing.JList jListBotOneChars;
	protected javax.swing.JList jListBotTwoBehaviors;
	protected javax.swing.JList jListBotTwoChars;
	public javax.swing.JPanel jPanelArea;
	private javax.swing.JPanel jPanelBotOne;
	private javax.swing.JPanel jPanelBotOne1;
	private javax.swing.JPanel jPanelContent;
	public javax.swing.JPanel jPanelGameArea;
	private javax.swing.JPanel jPanelGameButtons;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	// End of variables declaration//GEN-END:variables

}