/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TRunAway extends Token
{
    public TRunAway()
    {
        super.setText("run_away");
    }

    public TRunAway(int line, int pos)
    {
        super.setText("run_away");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRunAway(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRunAway(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRunAway text.");
    }
}
