/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ABlockLowFightActionType extends PFightActionType
{
    private TBlockLow _blockLow_;

    public ABlockLowFightActionType()
    {
        // Constructor
    }

    public ABlockLowFightActionType(
        @SuppressWarnings("hiding") TBlockLow _blockLow_)
    {
        // Constructor
        setBlockLow(_blockLow_);

    }

    @Override
    public Object clone()
    {
        return new ABlockLowFightActionType(
            cloneNode(this._blockLow_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockLowFightActionType(this);
    }

    public TBlockLow getBlockLow()
    {
        return this._blockLow_;
    }

    public void setBlockLow(TBlockLow node)
    {
        if(this._blockLow_ != null)
        {
            this._blockLow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockLow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockLow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockLow_ == child)
        {
            this._blockLow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockLow_ == oldChild)
        {
            setBlockLow((TBlockLow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
