/* Generated By:JavaCC: Do not edit this line. SafParser.java */
package parser;
import objects.*;
import java.lang.String;
import java.util.ArrayList;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.List;

public class SafParser implements SafParserConstants {
  public static void main(String args []) throws ParseException
  {
        try
        {
                String path  = new java.io.File(".").getCanonicalPath();
        String FightersFile = "fighters.txt";
                InputStream stream = new FileInputStream(path + "/src/parser/" + FightersFile);
                SafParser parser = new SafParser(stream);
        ArrayList<Fighter> f = parser.Start();
                Interpreter i = new Interpreter(f);
        i.Interpret();
        ImageUtil.loadImage(path + "/src/parser/test.gif");
        }
        catch(Exception e)
        {
          System.out.println("Exception:"+e);
        }
  }

  static final public ArrayList<Fighter> Start() throws ParseException {
    Token fighterName  = new Token();
    Token strengthName = new Token();
    Token strengValue = new Token();
    ArrayList<Fighter> fighters = new ArrayList<Fighter>();
    ArrayList<Condition> conditions = new ArrayList<Condition>();
    label_1:
    while (true) {
      fighterName = jj_consume_token(IDENTIFIER);
      jj_consume_token(OP_CURLY_BRACKETS);
                 Fighter f = new Fighter(fighterName.toString());
      label_2:
      while (true) {
        if (jj_2_1(2)) {
          strengthName = jj_consume_token(IDENTIFIER);
          jj_consume_token(ASSIGN);
          strengValue = jj_consume_token(PROP_VALUE);
                 f.setStrength(new Strength(strengthName.toString(),Integer.valueOf(strengValue.toString())));
        } else if (jj_2_2(2)) {
          conditions = searchForAndOrInConditions();
                 f.setConditions(conditions);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(CL_CURLY_BRACKETS);
                 fighters.add(f);
      if (jj_2_3(2)) {
        ;
      } else {
        break label_1;
      }
    }
    jj_consume_token(0);
                 {if (true) return fighters;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Condition> searchForAndOrInConditions() throws ParseException {
     Token conditionName = new Token();
     Token movesName = new Token();
     Token attacksName = new Token();
     Token conditionNameOr = new Token();
     Token conditionNameAnd = new Token();
     ArrayList conditionList=new ArrayList();
     List<Token> listMovesName = new ArrayList<Token>();
     List<Token> listAttacksName = new ArrayList<Token>();
     ArrayList<Condition> returnedCondition =new ArrayList<Condition>();
     int id=1;
    label_3:
    while (true) {
      if (jj_2_4(2)) {
        conditionName = jj_consume_token(IDENTIFIER);
        jj_consume_token(OP_BRACKETS);
        returnedCondition = conditions(conditionName,0,new Token());
        jj_consume_token(CL_BRACKETS);
      } else if (jj_2_5(2)) {
        conditionName = jj_consume_token(IDENTIFIER);
        jj_consume_token(OR);
        conditionNameOr = jj_consume_token(IDENTIFIER);
        jj_consume_token(OP_BRACKETS);
        returnedCondition = conditions(conditionName,0,conditionNameOr);
        jj_consume_token(CL_BRACKETS);
      } else if (jj_2_6(2)) {
        conditionName = jj_consume_token(IDENTIFIER);
        jj_consume_token(AND);
        conditionNameAnd = jj_consume_token(IDENTIFIER);
        jj_consume_token(OP_BRACKETS);
        returnedCondition = conditions(conditionName,id,conditionNameAnd);
        jj_consume_token(CL_BRACKETS);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_3;
      }
    }
         {if (true) return returnedCondition;}
    throw new Error("Missing return statement in function");
  }

  static final public ArrayList<Condition> conditions(Token conditionName,int id,Token conditionName2nd) throws ParseException {
    Token movesName = new Token();
    Token attacksName = new Token();
    ArrayList<Condition> returnedCondition = new ArrayList<Condition>();
    List<Token > listAttacksName = new ArrayList<Token>();
    List<Token > listMovesName = new ArrayList<Token>();
    label_4:
    while (true) {
      if (jj_2_7(2)) {
        movesName = jj_consume_token(IDENTIFIER);
        attacksName = jj_consume_token(IDENTIFIER);
                        if(id==0){returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));}
                        else
                        {returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));
                         returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));
                        }
      } else if (jj_2_8(2)) {
        movesName = jj_consume_token(IDENTIFIER);
        attacksName = jj_consume_token(IDENTIFIER);
                    if(id==0){returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));}
                    else
                    {returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));
                         returnedCondition.add(new Condition(conditionName2nd.toString(),movesName.toString(),attacksName.toString(),id));
                        }
      } else if (jj_2_9(2)) {
        movesName = jj_consume_token(IDENTIFIER);
        jj_consume_token(CHOOSE);
        jj_consume_token(OP_ROUND_BRACKETS);
        label_5:
        while (true) {
          attacksName = jj_consume_token(IDENTIFIER);
                                          listAttacksName.add(attacksName);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[2] = jj_gen;
            break label_5;
          }
        }
        jj_consume_token(CL_ROUND_BRACKETS);
                     for(Token oneOfListAttacks: listAttacksName)
                                {
                                        if(id==0){returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));}
                                        else
                                        {
                                                returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));
                                                returnedCondition.add(new Condition(conditionName2nd.toString(),movesName.toString(),attacksName.toString(),id));
                                        }
                            }
      } else if (jj_2_10(2)) {
        jj_consume_token(CHOOSE);
        jj_consume_token(OP_ROUND_BRACKETS);
        label_6:
        while (true) {
          movesName = jj_consume_token(IDENTIFIER);
                                        listMovesName.add(movesName);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[3] = jj_gen;
            break label_6;
          }
        }
        jj_consume_token(CL_ROUND_BRACKETS);
        attacksName = jj_consume_token(IDENTIFIER);
                    for(Token oneOfListMoves: listMovesName)
                    {
                                if(id==0){returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));}
                                else
                                {
                                        returnedCondition.add(new Condition(conditionName2nd.toString(),movesName.toString(),attacksName.toString(),id));
                                        returnedCondition.add(new Condition(conditionName2nd.toString(),movesName.toString(),attacksName.toString(),id));
                                }

                         }
      } else if (jj_2_11(2)) {
        jj_consume_token(CHOOSE);
        jj_consume_token(OP_ROUND_BRACKETS);
        label_7:
        while (true) {
          movesName = jj_consume_token(IDENTIFIER);
                                listMovesName.add(movesName);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_7;
          }
        }
        jj_consume_token(CL_ROUND_BRACKETS);
        jj_consume_token(CHOOSE);
        jj_consume_token(OP_ROUND_BRACKETS);
        label_8:
        while (true) {
          attacksName = jj_consume_token(IDENTIFIER);
                                  listAttacksName.add(attacksName);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case IDENTIFIER:
            ;
            break;
          default:
            jj_la1[5] = jj_gen;
            break label_8;
          }
        }
        jj_consume_token(CL_ROUND_BRACKETS);
                    for(Token oneOfListMoves: listMovesName)
                        {
                            for(Token oneOfListAttacks: listAttacksName)
                                {
                                        if(id==0)
                                        {returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));}
                                        else
                                        {returnedCondition.add(new Condition(conditionName.toString(),movesName.toString(),attacksName.toString(),id));
                                         returnedCondition.add(new Condition(conditionName2nd.toString(),movesName.toString(),attacksName.toString(),id));
                                        }

                            }
                        }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHOOSE:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
    }
                 {if (true) return returnedCondition;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_3_6() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(AND)) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    Token xsp;
    if (jj_3R_10()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_10()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(CHOOSE)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_scan_token(CHOOSE)) return true;
    if (jj_scan_token(OP_ROUND_BRACKETS)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(OR)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(OP_CURLY_BRACKETS)) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(OP_BRACKETS)) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_scan_token(CHOOSE)) return true;
    if (jj_scan_token(OP_ROUND_BRACKETS)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SafParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[7];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10000,0x10000,0x10000,0x10000,0x10000,0x10000,0x11000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[11];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SafParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SafParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SafParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SafParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SafParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SafParser(SafParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SafParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 7; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[23];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 7; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 23; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 11; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
