/* Generated By:JavaCC: Do not edit this line. SafParserTreeConstants.java Version 5.0 */
package parser;

public interface SafParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONTENTS = 1;


  public String[] jjtNodeName = {
    "Start",
    "contents",
  };
}
/* JavaCC - OriginalChecksum=89f61c4409ff01cfe4cac26c0e9d96e3 (do not edit this line) */
