-----------------
- Prerequisites -
-----------------

- JDK 1.6
- Eclipse
- (Optional) ANTLR builder for (re)building the FDL lexer/parser.
- (Optional) JUnit for unit testing.

----------------------
- Build Instructions -
----------------------

1. Open project in eclipse
2. Press Ctrl+B
3. (Optional) Package binaries into JAR.
- You have now built stuff!

(Build scripts coming Soon™)