/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class ASingleFightActionProgramFightAction extends PProgramFightAction
{
    private PFightActionType _fightActionType_;

    public ASingleFightActionProgramFightAction()
    {
        // Constructor
    }

    public ASingleFightActionProgramFightAction(
        @SuppressWarnings("hiding") PFightActionType _fightActionType_)
    {
        // Constructor
        setFightActionType(_fightActionType_);

    }

    @Override
    public Object clone()
    {
        return new ASingleFightActionProgramFightAction(
            cloneNode(this._fightActionType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleFightActionProgramFightAction(this);
    }

    public PFightActionType getFightActionType()
    {
        return this._fightActionType_;
    }

    public void setFightActionType(PFightActionType node)
    {
        if(this._fightActionType_ != null)
        {
            this._fightActionType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fightActionType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fightActionType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fightActionType_ == child)
        {
            this._fightActionType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fightActionType_ == oldChild)
        {
            setFightActionType((PFightActionType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
