/* Generated By:JavaCC: Do not edit this line. SafConstants.java */
package saf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SafConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGNMENT = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int CHOOSE = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int PROPERTYVALUE = 11;
  /** RegularExpression Id. */
  int OPENPARENTHESIS = 12;
  /** RegularExpression Id. */
  int CLOSEPARENTHESIS = 13;
  /** RegularExpression Id. */
  int OPENCURLYBRACKET = 14;
  /** RegularExpression Id. */
  int CLOSECURLYBRACKET = 15;
  /** RegularExpression Id. */
  int OPENSQAREBRACKET = 16;
  /** RegularExpression Id. */
  int CLOSESQAREBRACKET = 17;
  /** RegularExpression Id. */
  int INVALIDCHAR = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"=\"",
    "\"and\"",
    "\"or\"",
    "\"choose\"",
    "<IDENTIFIER>",
    "<PROPERTYVALUE>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<INVALIDCHAR>",
  };

}
