/* Generated By:JavaCC: Do not edit this line. SafTreeConstants.java Version 5.0 */
package saf;

public interface SafTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTRENGTH = 1;
  public int JJTBEHAVIOR = 2;


  public String[] jjtNodeName = {
    "Parse",
    "Strength",
    "Behavior",
  };
}
/* JavaCC - OriginalChecksum=9bc262bb4bfeb8b285e30d7fe8873a91 (do not edit this line) */
