/* This file was generated by SableCC (http://www.sablecc.org/). */

package saf.node;

import saf.analysis.*;

@SuppressWarnings("nls")
public final class TKickHigh extends Token
{
    public TKickHigh()
    {
        super.setText("kick_high");
    }

    public TKickHigh(int line, int pos)
    {
        super.setText("kick_high");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKickHigh(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKickHigh(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKickHigh text.");
    }
}
